if(NOT USE_CUSTOM_CMAKE)
    cmake_minimum_required(VERSION 3.21)
    include($ENV{XMOS_CMAKE_PATH}/xcommon.cmake)
    project(fwk_voice_tests)

    add_subdirectory(lib_agc)
    add_subdirectory(lib_ns)
    add_subdirectory(lib_ic)
    add_subdirectory(lib_vnr)
    add_subdirectory(lib_aec)
    add_subdirectory(lib_adec)
    if(NOT BUILD_NATIVE)
        add_subdirectory( pipeline )
    endif()
else()
    enable_language(CXX C ASM)
    set(XCORE_MATH_PATH ${CMAKE_SOURCE_DIR}/..) # Expected to have been fetched in the sandbox as part of xcommon cmake build
    add_subdirectory(${XCORE_MATH_PATH}/lib_xcore_math/lib_xcore_math ${CMAKE_BINARY_DIR}/lib_xcore_math)
    add_subdirectory(custom_cmake_build)
endif()
