cmake_minimum_required(VERSION 3.21)
include($ENV{XMOS_CMAKE_PATH}/xcommon.cmake)
project(fwk_voice_tests)

include(${CMAKE_CURRENT_LIST_DIR}/etc/build_options.cmake)

if("${TEST_BUILD_PART}" STREQUAL "all" OR "${TEST_BUILD_PART}" STREQUAL "partA")
    add_subdirectory(lib_agc)
    add_subdirectory(lib_ns)
    add_subdirectory(lib_ic)
    add_subdirectory(lib_vnr)
    add_subdirectory(lib_adec)
endif()

if("${TEST_BUILD_PART}" STREQUAL "all" OR "${TEST_BUILD_PART}" STREQUAL "partB")
    add_subdirectory(lib_aec)
    if(NOT BUILD_NATIVE)
        add_subdirectory( pipeline )
        add_subdirectory( profile_memory )
        add_subdirectory( profile_mips )
    endif()
endif()
