/* Do not edit, autogenerated */ 
#include "aec_schedule.h"

aec_task_distribution_t tdist = {
	.thread_count = 1,
	.passes_for_3_tasks_and_channels = 6,
	.par_3_tasks_and_channels = {
		{{0, 0, 1},{1, 0, 1},{2, 0, 1},{0, 1, 1},{1, 1, 1},{2, 1, 1},},
	},
	.passes_for_2_tasks_and_channels = 4,
	.par_2_tasks_and_channels = {
		{{0, 0, 1},{1, 0, 1},{0, 1, 1},{1, 1, 1},},
	},
	.passes_for_1_tasks_and_channels = 2,
	.par_1_tasks_and_channels = {
		{{0, 0, 1},{0, 1, 1},},
	},
	.passes_for_3_tasks = 3,
	.par_3_tasks = {
		{{0, 1},{1, 1},{2, 1},},
	},
	.passes_for_2_tasks = 2,
	.par_2_tasks = {
		{{0, 1},{1, 1},},
	},
};

